### ISSUE TITLE
this is bug ??

### ISSUE THREAD

**Issue by hawklin2017** [VolantMQ/persistence-boltdb#1]
https://github.com/VolantMQ/persistence-boltdb/blob/e4f13adb11cae34b1436a04b81e9c37b490acd05/sessions.go#L328

1, please check if bucket  named bucketSubscriptions  does exist，as i know，bucketSubscriptions is name of the bucket‘s key, according to line 50:"session.Put(bucketSubscriptions, data)" 

2, the variable “tx” is root bucket，buck := tx.Bucket(bucketSubscriptions), "buck" is always equal with nil

**Comment by troian** [comment]
It's not a bug
tx.Bucket returns nil if bucket does not exist
